### ISSUE TITLE
Actualización de  CSS

### ISSUE THREAD

**Issue by hipema** [lasrecetasdelabuelaLM/recetasdelabuela#1]
https://github.com/lasrecetasdelabuelaLM/recetasdelabuela/blob/8aec0102f0e555d638b825e673dc9529b026fc23/css/style.css#L1

Buenas Mané, te adjunto el código de css modificado para que lo adjuntes al archivo de estilo.

    <style>
    
    body {
        font-family: 'Arvo', serif;
    }
    /* Estilos correspondientes a la cabecera */
    .cabecera {
        background-color: #e8bc65;
        padding: 15px;
        padding-left: 4%;
    }
    .imagen-cabecera {
        width: 75%;
        max-width: 950px;
    }
    .redes-sociales {
        max-width: 50px;
        width: 30%;
    }
    .menu_navegacion {
        width: 100%;
        background-color: #dc982f;
    }
    /* Estilos de diseño de secciones */
    h1 {
        font-family: 'Zhi Mang Xing', cursive;
        font-size: 35px;
    }

    /* Estilos correspondientes al menú de navegación*/
    ul {
    list-style-type: none;
    margin: 1px;
    padding: 1px;
    overflow: hidden;
    }

    li {
        float: left;
    }

    li a {
       display:block;
       color: black; 
       text-align: center;
       padding: 14px 16px;
       text-decoration: none;
    }

    li a:hover {
        font-style: italic;
        color: grey;
    }
    </style>

**Comment by mbritTech** [comment]
Ya está actualizado el archivo index.
